apiVersion: v1
kind: Service
metadata:
  name: confluent-schema-registry 
  labels:
    app: confluent-schema-registry 
spec:
  ports:
  - nodePort: 30001
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: confluent-schema-registry
  type: NodePort
