apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-ui
spec:
  selector:
    matchLabels:
      app: schema-registry-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry-ui
    spec:
      containers:
      - name: schema-registry-ui
        image: landoop/schema-registry-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: SCHEMAREGISTRY_URL
          value: http://confluent-schema-registry:8081/
        - name: PROXY 
          value: "true"
        - name: ALLOW_GLOBAL 
          value: "true"
        - name: ALLOW_TRANSITIVE 
          value: "true"
        - name: ALLOW_DELETION 
          value: "true"
