apiVersion: v1
kind: Service
metadata:
  name: schema-registry-ui
  labels:
    app: schema-registry-ui
spec:
  ports:
  - nodePort: 30000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: schema-registry-ui
  type: NodePort
